In [1]:
%reload_ext autoreload
%autoreload 2

from google.colab import drive
drive.mount('/content/drive')

import os
GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = 'My_AI4Top/Top-invar-DL'
GOOGLE_DRIVE_PATH = os.path.join(
    'drive', 'My Drive', GOOGLE_DRIVE_PATH_AFTER_MYDRIVE)
print(GOOGLE_DRIVE_PATH)

import sys
sys.path.append(GOOGLE_DRIVE_PATH)

import torch
if torch.cuda.is_available:
    device = 'cuda'
    print('Good to go')
else:
    device = 'cpu'
    print('Please set Gpu via Edit -> Notebook Setting')


Mounted at /content/drive
drive/My Drive/My_AI4Top/Top-invar-DL
Good to go


In [ ]:
!git clone --branch dev https://github.com/Junang-Wang/Top-invar-DL.git

(1, 2, 3, 1, 2, 3)

In [ ]:
del Graphene_params
del Graphene_SS_Gen



NameError: ignored

In [ ]:
torch.cuda.empty_cache()
torch.cuda.memory_allocated()

15262712320

In [2]:
from Graphene_Generator_v3_Gpu import *
torch.cuda.empty_cache()
device = 'cuda'
t = torch.arange(10,52,2) 
#t = torch.tensor([16])
t_unique = t.shape[0]

Delta = 1
B_steps = 25 
mu_steps = 25
mu_random = 101
B = torch.linspace(-5,5,B_steps)
mu_0 = torch.linspace(1e-10,10,mu_random)
mu_offset = torch.linspace(-5,5,mu_steps)
mu_truck = 3
mu_div = mu_random//mu_truck
nx, ny = 500, 500
Graphene_D = torch.zeros(t_unique,mu_random,mu_steps,B_steps)
for i in range(t_unique):
    for j in range(mu_div):
        Graphene_params = Graphene_Vec(t[i:i+1], mu_0[j*mu_truck:(j+1)*mu_truck], mu_offset, B, nx, ny, Delta, device='cuda')
        Graphene_SS_Gen = Graphene_SS(Graphene_params,device='cuda')
        Graphene_D[i,j*mu_truck:(j+1)*mu_truck] = Graphene_SS_Gen.total()
        del Graphene_params
        del Graphene_SS_Gen
        torch.cuda.empty_cache()
    if j == mu_div-1 and mu_random%mu_truck != 0:
        Graphene_params = Graphene_Vec(t[i:i+1], mu_0[(j+1)*mu_truck:], mu_offset, B, nx, ny, Delta, device='cuda')
        Graphene_SS_Gen = Graphene_SS(Graphene_params,device='cuda')
        Graphene_D[i,(j+1)*mu_truck:] = Graphene_SS_Gen.total()
        del Graphene_params
        del Graphene_SS_Gen
        torch.cuda.empty_cache()

Graphene_labels = torch.cat((2*torch.ones(mu_random*t_unique,1),mu_0.reshape(-1,1).repeat(t_unique,1)),dim=1)

Graphene_D = Graphene_D.reshape(t_unique*mu_random,1,B_steps,mu_steps)



In [4]:
Graphene_D_path = os.path.join(GOOGLE_DRIVE_PATH,'Graphene_D.pt')
Graphene_label_path = os.path.join(GOOGLE_DRIVE_PATH,'Graphene_label.pt')
torch.save(Graphene_D,Graphene_D_path)
torch.save(Graphene_labels,Graphene_label_path)

In [ ]:
Graphene_D[101]

tensor([[[ 6.4250e-02,  8.9483e-02,  1.0396e-01, -9.4683e-02,  2.2325e-01,
           2.4651e-01,  4.1715e-01,  6.3977e-01,  2.2458e-01, -6.3758e+00,
           6.2347e+00,  6.2349e+00,  6.2350e+00,  6.2349e+00,  6.2347e+00,
          -6.3758e+00,  2.2458e-01,  6.3977e-01,  4.1715e-01,  2.4651e-01,
           2.2325e-01, -9.4683e-02,  1.0396e-01,  8.9483e-02,  6.4250e-02],
         [-2.7412e-01, -1.0961e-02,  1.2125e-01,  1.6122e-01,  1.8762e-01,
           2.8726e-01,  3.1733e-01,  5.4166e-01,  8.0605e-01, -5.1673e-01,
           6.2219e+00,  6.2221e+00,  6.2221e+00,  6.2221e+00,  6.2219e+00,
          -5.1673e-01,  8.0605e-01,  5.4166e-01,  3.1733e-01,  2.8726e-01,
           1.8762e-01,  1.6122e-01,  1.2125e-01, -1.0961e-02, -2.7412e-01],
         [-1.0555e-01, -6.0943e-02,  1.0456e-01, -1.5766e-01, -2.9249e-01,
           2.8564e-01,  3.3229e-01,  6.7583e-01, -3.1954e-01, -3.3170e+01,
           6.1887e+00,  6.1889e+00,  6.1890e+00,  6.1889e+00,  6.1887e+00,
          -3.3170e+01, 

In [ ]:
D_inter_xx, D_inter_xy, D_inter_yy

(tensor([[[[-0.0773, -0.0352,  0.2366,  0.2367,  0.2366, -0.0352, -0.0773],
           [-0.1103, -0.0851,  0.2885,  0.2886,  0.2885, -0.0851, -0.1103],
           [-0.1508, -0.0594,  0.3508,  0.3509,  0.3508, -0.0594, -0.1508],
           [ 0.0569, -0.5477,  0.3738,  0.3987,  0.3738, -0.5477,  0.0569],
           [-0.1508, -0.0594,  0.3508,  0.3509,  0.3508, -0.0594, -0.1508],
           [-0.1103, -0.0851,  0.2885,  0.2886,  0.2885, -0.0851, -0.1103],
           [-0.0773, -0.0352,  0.2366,  0.2367,  0.2366, -0.0352, -0.0773]]]]),
 tensor([[[[-1.1832e-11, -1.2696e-11,  4.7132e-11,  4.8965e-11,  4.7132e-11,
            -1.2696e-11, -1.1832e-11],
           [ 3.9637e-12, -9.7752e-12, -1.7047e-11, -1.7285e-11, -1.7047e-11,
            -9.7752e-12,  3.9637e-12],
           [ 2.6345e-11, -2.1696e-11, -3.4809e-11, -3.8743e-11, -3.4809e-11,
            -2.1696e-11,  2.6345e-11],
           [ 4.4250e-10,  2.2993e-09, -2.4796e-11, -4.8399e-11, -2.4796e-11,
             2.2993e-09,  4.4250e-10],


In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import matplotlib
kx, ky = Graphene_params.kx.reshape(-1), Graphene_params.ky.reshape(-1)
#epsilon = Graphene_params.epsilon_0.reshape(nx, ny)
x, y = torch.meshgrid(kx, ky, indexing='ij')
#ax = plt.axes(projection='3d')
def plot_epsilon(t):
    epsilon = t*torch.sqrt(abs(3+2*torch.cos(sqrt(3)*y) + 4 *
                  torch.cos(sqrt(3)/2*y)*torch.cos(3/2*x)))
    masker_epsilon_cutoff = torch.zeros_like(epsilon)
    masker_epsilon_cutoff[epsilon <=1000] = 1
    
    masked_epsilon = masker_epsilon_cutoff*epsilon
    fig = plt.figure()
    ax = plt.axes(projection='3d')
    surf = ax.plot_surface(x, y, masked_epsilon, cmap=matplotlib.cm.coolwarm)
    cset = ax.contourf(x,y,epsilon,zdir='z',offset = 0,cmap=matplotlib.cm.coolwarm)
    fig.colorbar(surf,ax=ax)
    plt.show()
    #ax.clear()
    


In [ ]:
%matplotlib widget
import ipywidgets 
ipywidgets.interact(plot_epsilon,t=10000)
#plt.show()

interactive(children=(IntSlider(value=10000, description='t', max=30000, min=-10000), Output()), _dom_classes=…

<function __main__.plot_epsilon(t)>

In [ ]:
D_intra_xx, D_intra_xy, D_intra_yy


(tensor([[[[1.0273]]]]), tensor([[[[-6.0547e-08]]]]), tensor([[[[1.0248]]]]))

In [ ]:
D_inter_xx, D_inter_yy, D_inter_xy


(tensor([[[[4.3910]]]]), tensor([[[[4.3948]]]]), tensor([[[[1.1719e-08]]]]))

In [ ]:
D_total_xx, D_total_yy, D_total_xy


(tensor([[[[5.4895]]]]), tensor([[[[nan]]]]), tensor([[[[2.1484e-08]]]]))

In [ ]:
4/torch.pi


1.2732395447351628

In [ ]:
D_intra_xy, D_inter_xy


(tensor([[[[0.0681]]]], device='cuda:0'),
 tensor([[[[0.2435]]]], device='cuda:0'))